name=CameraBrick
version=2.0.0
author=Dmitry Akulov
maintainer=Dmitry Akulov <pink0d.github@gmail.com>
sentence=WiFi FPV control for ESP32CAM and Mould King modules
paragraph=This library features WiFi FPV with gamepad controls for Mould King modules
category=Device Control
url=https://github.com/pink0D/CameraBrick
architectures=esp32
includes=CameraBrick.h
depends=MouldKingino (>=1.3.0)
